### ISSUE TITLE
Unable to connect to broker

### ISSUE THREAD

**Issue by pizza-hut** [CloudKarafka/java-kafka-example#1]
Hello,
I created a Developer Duck kafka instance in CloudKafka and also a topic. I get the following:

"Consumer clientId=consumer-1, groupId=] Connection to node -1 could not be established. Broker may not be available."

I followed your properties and security properties are the same:
props.put("security.protocol", "SASL_SSL");
props.put("sasl.mechanism", "SCRAM-SHA-256");
props.put("sasl.jaas.config", jaasCfg);

(of course, pointing to my own hostname and using my own credentials in jaasCfg)

Is there something I miss out?

**Comment by carlhoerberg** [comment]
Please email support@cloudkarafka.com with your hostname/username
