### ISSUE TITLE
Could not get messages from consumer 

### ISSUE THREAD

**Issue by andynhuttran** [CloudKarafka/java-kafka-example#2]
I try the code with Kafka cloud from http://cloudkarafka.com. it is not working.
However, I set up a local Kafka from apache Kafka, the code works well with changing brokers and topic name.

Could you tell me what i should to do with Kafka cloud from http://cloudkarafka.com?

**Comment by dentarg** [comment]
We need more information than "it is not working". Feel free to [contact support](https://www.cloudkarafka.com/support.html) if you have any issues with CloudKarafka.
